// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
let limit = 4000000;
sum = 0;
let array = [];

let f1 = 1;
let f2 = 2;
let f3 = 2;
let i = 1;
while (f3 < limit) {
  if (i > 1) {
    evenSum(f3);
    f3 = f1 + f2;
    f1 = f2;
    f2 = f3;
  } else evenSum(i);
  i++;
}

function evenSum(number) {
  if (number % 2 == 0) {
    sum += number;
    array.push(number);
  }
}

console.log(
  `Terms in the Fibonacci sequence whose values do not exceed ${limit} are`
);
console.log(...array);
console.log(`Sum of the even-valued terms is ${sum}`);
